apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - env:
        - name: ENCRYPT_KEY
          value: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo
        image: us-central1-docker.pkg.dev/sensor-project-334918/ostock/configserver:latest
        name: configserver
        ports:
        - containerPort: 8071


---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  type: NodePort
  selector:
    app: configserver
  ports:
  - name: "8071"
    port: 8071
    targetPort: 8071
    nodePort: 31000